update branch

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -189,6 +189,19 @@ install_prereqs() {
   # install Ansible (and dependencies)
   echo -n "--> Validating package dependencies: "
   if [ "${platform}" == "centos" ]; then
+    # check for packages with known conflicts
+    conflict_pkgs="PyYAML python-requests python-ipaddress"
+    for pkg in ${conflict_pkgs}; do
+      rpm -q "${pkg}" > /dev/null 2>&1
+      if [ $? -eq 0 ]; then
+        sudo rpm -e ${pkg} --nodeps > ${log} 2>&1
+        if [ $? -ne 0 ]; then
+          echo -e "\nERROR: failed to uninstall ${pkg} - here's the last 10 lines of the log:\n"
+          tail -20 ${log}; exit 1
+        fi
+      fi
+    done
+
     for pkg in epel-release ntp nginx gcc python-devel python2-pip bc; do
       echo -n "${pkg} "
       rpm -q ${pkg} > /dev/null 2>&1
@@ -208,19 +221,6 @@ install_prereqs() {
       tail -10 ${log}; exit 1
     fi
 
-    # check for packages with known conflicts
-    conflict_pkgs="PyYAML python-requests python-ipaddress"
-    for pkg in ${conflict_pkgs}; do
-      rpm -q "${pkg}" > /dev/null 2>&1
-      if [ $? -eq 0 ]; then
-        sudo rpm -e ${pkg} --nodeps > ${log} 2>&1
-        if [ $? -ne 0 ]; then
-          echo -e "\nERROR: failed to uninstall ${pkg} - here's the last 10 lines of the log:\n"
-          tail -20 ${log}; exit 1
-        fi
-      fi
-    done
-
     ## install additional pip-based packages
     for pkg in shade docker-py; do
       echo -n "${pkg} "
@@ -232,7 +232,6 @@ install_prereqs() {
     done
 
     ## install additional yum-based packages
-    #for pkg in python-requests python-ipaddress ansible; do
     for pkg in ansible; do
       echo -n "${pkg} "
       sudo yum -y install ${pkg} > ${log} 2>&1
@@ -241,6 +240,16 @@ install_prereqs() {
         tail -10 ${log}; exit 1
       fi
     done
+
+    ## install additional pip-based packages
+    #for pkg in requests ipaddress; do
+    #  echo -n "${pkg} "
+    #  sudo pip install ${pkg} > ${log} 2>&1
+    #  if [ $? -ne 0 ]; then
+    #    echo -e "\nERROR: failed to install ${pkg} - here's the last 10 lines of the log:\n"
+    #    tail -10 ${log}; exit 1
+    #  fi
+    #done
 
     ## install setupd
     echo -n "setupd"
