update INSTALL to handle shade dependencies

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -258,21 +258,25 @@ install_prereqs() {
     tail -10 ${log}; exit 1
   fi
 
-  ## install python shade
-  echo -n "python-shade "
-  sudo pip install shade > ${log} 2>&1
-  if [ $? -ne 0 ]; then
-    echo -e "\nERROR: failed to install python shade - here's the last 10 lines of the log:\n"
-    tail -10 ${log}; exit 1
-  fi
+  ## install additional pip-based packages
+  for pkg in shade docker-py; do
+    echo -n "${pkg} "
+    sudo pip install ${pkg} > ${log} 2>&1
+    if [ $? -ne 0 ]; then
+      echo -e "\nERROR: failed to install ${pkg} - here's the last 10 lines of the log:\n"
+      tail -10 ${log}; exit 1
+    fi
+  done
 
-  ## install python docker-py
-  echo -n "docker-py "
-  sudo pip install docker-py > ${log} 2>&1
-  if [ $? -ne 0 ]; then
-    echo -e "\nERROR: failed to install python docker-py - here's the last 10 lines of the log:\n"
-    tail -10 ${log}; exit 1
-  fi
+  ## install additional yum-based packages
+  for pkg in python-requests python-ipaddress; do
+    echo -n "${pkg} "
+    sudo yum -y install ${pkg} > ${log} 2>&1
+    if [ $? -ne 0 ]; then
+      echo -e "\nERROR: failed to install ${pkg} - here's the last 10 lines of the log:\n"
+      tail -10 ${log}; exit 1
+    fi
+  done
 
   ## install setupd
   echo -n "setupd"
