update branch

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -202,20 +202,21 @@ install_prereqs() {
     done
 
     # check for packages with known conflicts
-    #conflict_pkgs="PyYAML python-requests python-ipaddress"
-    #for pkg in ${conflict_pkgs}; do
-    #  rpm -q "${pkg}" > /dev/null 2>&1
-    #  if [ $? -eq 0 ]; then
-    #    sudo rpm -e --nodeps ${pkg} > ${log} 2>&1
-    #    if [ $? -ne 0 ]; then
-    #      echo -e "\nERROR: failed to uninstall ${pkg} - here's the last 10 lines of the log:\n"
-    #      tail -20 ${log}; exit 1
-    #    fi
-    #  fi
-    #done
+    conflict_pkgs="python-requests python-ipaddress"
+    for pkg in ${conflict_pkgs}; do
+      rpm -q "${pkg}" > /dev/null 2>&1
+      if [ $? -eq 0 ]; then
+        sudo yum -y remove ${pkg} > ${log} 2>&1
+        if [ $? -ne 0 ]; then
+          echo -e "\nERROR: failed to uninstall ${pkg} - here's the last 10 lines of the log:\n"
+          tail -20 ${log}; exit 1
+        fi
+      fi
+    done
 
     # clean yum
-    #sudo yum clean all
+    #sudo yum clean all > /dev/null 2>&1
+    #sudo rm -rf /var/cache/yum/*
 
     # install additional yum-based packages
     for pkg in python-devel python2-pip bc; do
