removed setupd packages for Ubuntu control host install

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -236,6 +236,26 @@ install_prereqs() {
       tail -10 ${log}; exit 1
     fi
     echo
+
+    # update setupd packages
+    echo -n "--> Updating setupd libraries: "
+    for pkg in pf9_master_setup.py pf9_utils.py pf9_mgmt_setup.py; do
+      echo -n "${pkg} "
+      sudo /bin/cp -f ${basedir}/scripts/setupd-updates/${pkg} \
+           /opt/pf9/setupd/lib/python2.7/site-packages/setupd_samples/utils/${pkg} > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo; assert "failed to update ${pkg}"
+      fi
+    done
+  
+    for pkg in attach-node add-cluster; do
+      echo -n "${pkg} "
+      sudo /bin/cp -f ${basedir}/scripts/setupd-updates/${pkg} /opt/pf9/setupd/bin/${pkg} > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo; assert "failed to update ${pkg}"
+      fi
+    done
+    echo
   elif [ "${platform}" == "ubuntu" ]; then
     # add ansible repository
     dpkg-query -f '${binary:Package}\n' -W | grep ^${pkg}$ > /dev/null 2>&1
@@ -260,38 +280,11 @@ install_prereqs() {
         fi
       fi
     done
-
-    ## install setupd
-    echo -n "setupd"
-    if [ ! -r /opt/pf9 ]; then mkdir -p /opt/pf9; fi
-    if [ ! -r /opt/pf9/setupd ]; then 
-      cp -r ${basedir}/lib/setupd /opt/pf9
-    fi
     echo
   fi
 
   # create log directory
   if [ ! -d /var/log/pf9 ]; then sudo mkdir -p /var/log/pf9; fi
-
-  # update setupd packages
-  echo -n "--> Updating setupd libraries: "
-  for pkg in pf9_master_setup.py pf9_utils.py pf9_mgmt_setup.py; do
-    echo -n "${pkg} "
-    sudo /bin/cp -f ${basedir}/scripts/setupd-updates/${pkg} \
-         /opt/pf9/setupd/lib/python2.7/site-packages/setupd_samples/utils/${pkg} > /dev/null 2>&1
-    if [ $? -ne 0 ]; then
-      echo; assert "failed to update ${pkg}"
-    fi
-  done
-
-  for pkg in attach-node add-cluster; do
-    echo -n "${pkg} "
-    sudo /bin/cp -f ${basedir}/scripts/setupd-updates/${pkg} /opt/pf9/setupd/bin/${pkg} > /dev/null 2>&1
-    if [ $? -ne 0 ]; then
-      echo; assert "failed to update ${pkg}"
-    fi
-  done
-  echo
 }
 
 ################################################################################
