updated INSTALL script

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -71,7 +71,8 @@ getYN() {
 ################################################################################
 ## main
 ################################################################################
-# validate 
+
+## validate commandline arguments
 if [ $# -ne 1 ]; then usage; fi
 while [ $# -gt 0 ]; do
   case ${1} in
@@ -83,14 +84,14 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-# validate running on CentOS
+## validate running on CentOS
 if [ ! -r /etc/redhat-release ]; then assert "This script only runs on  RedHat or CentOS"; fi
 
-# validate sudo priviledges
+## validate sudo priviledges
 sudo bash <<< "exit 200"
 if [ $? -ne 200 ]; then assert "you need sudo privilidges to run this script - please update /etc/sudoers"; fi
 
-# search for target in Ansible inventory
+## search for target in Ansible inventory
 grep ^${target} ${inventory} > /dev/null 2>&1
 if [ $? -eq 0 ]; then
   target_type="host"
@@ -99,7 +100,7 @@ else
   if [ $? -eq 0 ]; then target_type="group"; fi
 fi
 
-# validate target found
+## validate target found
 case ${target_type} in
 host|group)
   ;;
@@ -108,51 +109,48 @@ host|group)
   ;;
 esac
 
-# validate Ansible is installed
-which ansible > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-  getYN "Ansible is not installed - would you like to install it now? "
-  if [ $? -ne 0 ]; then assert "Install Ansible and re-run this script - aborting"; fi
+## validate package dependencies
+getYN "Ansible is not installed - would you like to install it now? "
+if [ $? -ne 0 ]; then assert "Install Ansible and re-run this script - aborting"; fi
 
-  # install Ansibl (and dependencies)
-  echo -n "--> Installing Ansible and dependencies: "
-  for pkg in epel-release ansible gcc python-devel python2-pip bc; do
-    echo -n "${pkg} "
-    rpm -q ${pkg} > /dev/null 2>&1
+# install Ansibl (and dependencies)
+echo -n "--> Installing Ansible and dependencies: "
+for pkg in epel-release ansible gcc python-devel python2-pip bc; do
+  echo -n "${pkg} "
+  rpm -q ${pkg} > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    sudo yum -y install ${pkg} > ${log} 2>&1
     if [ $? -ne 0 ]; then
-      sudo yum -y install ${pkg} > ${log} 2>&1
-      if [ $? -ne 0 ]; then
-        echo -e "ERROR: failed to install ${pkg} - here's the log:\n"
-        cat ${log}; exit 1
-      fi
+      echo -e "ERROR: failed to install ${pkg} - here's the log:\n"
+      cat ${log}; exit 1
     fi
-  done
-
-  # upgrade pip
-  sudo pip install --upgrade pip > ${log} 2>&1
-  if [ $? -ne 0 ]; then
-    echo -e "ERROR: failed to upgrade pip - here's the log:\n"
-    cat ${log}; exit 1
   fi
+done
 
-  # install python shade
-  echo -n "python-shade "
-  sudo pip install shade > ${log} 2>&1
-  if [ $? -ne 0 ]; then
-    echo -e "ERROR: failed to install python shade - here's the log:\n"
-    cat ${log}; exit 1
-  fi
-  echo
+## upgrade pip
+sudo pip install --upgrade pip > ${log} 2>&1
+if [ $? -ne 0 ]; then
+  echo -e "ERROR: failed to upgrade pip - here's the log:\n"
+  cat ${log}; exit 1
 fi
 
-# validate minimum Ansible version
+## install python shade
+echo -n "python-shade "
+sudo pip install shade > ${log} 2>&1
+if [ $? -ne 0 ]; then
+  echo -e "ERROR: failed to install python shade - here's the log:\n"
+  cat ${log}; exit 1
+fi
+echo
+
+## validate minimum Ansible version
 ansible_version=$(ansible --version | head -1 | cut -d ' ' -f2 | cut -d . -f1-2)
 if (( ! $(bc <<< "$ansible_version >= $min_ansible_version") )); then assert "Ansible ${min_ansible_version} or greater is required"; fi
 
-# call pf9-autopdeplopy
+## call pf9-autopdeplopy
 banner
 echo -e "\n[Executing: ansible-playbook -i ${inventory} -l ${target} ${autodeplopy_script}]"
 ansible-playbook -i ${inventory} -l ${target} ${autodeplopy_script}
 
-# exit cleanly
+## exit cleanly
 exit 0
